name: Augusta's Elite Boot Camp
favicon: null
layout_spectrum: 0.908303810749203
typography_spectrum: 0.6159010655246675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#218cff'
    - '#ffe7c7'
    - '#020605'
    - '#b8b9be'
    - '#575864'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
