typography_spectrum: 0.79188
color:
  brandColors:
    - '#218cff'
    - '#ffe7c7'
    - '#020605'
    - '#b8b9be'
    - '#575864'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.01046
analytics:
  google: null
  facebook: null
  twitter: null
name: Augusta's Elite Boot Camp
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: 2ac5ea26-575c-4db2-b1c7-6aef212447d0
    type: content
  - name: Places To heck Out
    url: 'http://augustaselitebootcamp.com'
    type: external
favicon: null
purpose: []
